name: Deploy

on:
  workflow_dispatch:

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-2.12.0-4.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.12.0-4.1.pre
      - name: Build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com          
          cd webapp
          git checkout main
          git pull
          cd ${{ github.workspace }}
          git add .
          git commit -m "Automatic update submodules"
          git push origin main --force
          flutter config --build-dir=../build
          flutter config --enable-web
          cd webapp
          flutter build web --release
          cd ${{ github.workspace }}
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-page --force
